# =================================
# SDN Frontend Docker Compose
# =================================

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    container_name: sdn-frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sdn-network

networks:
  sdn-network:
    driver: bridge